### ISSUE TITLE
额。。。laravist也是基础免费，进阶收费而已

### ISSUE THREAD

**Issue by JellyBool** [mangoim/Laravel-sites#1]
像laravel的基础教程，还有之前录的vuejs教程都是免费的。这样写laravist，我不服！！！！！！

**Comment by crazyLQ** [comment]
额... 据说价格比较贵,  有点抹黑的意思吧?
没错, 我就是laravist的用户,  一个系列视频几十, 貌似最多的也就150吧?, 可是我还是买了, 觉得值, 
我也不是壕,  作为入门学习laravel的PHPer,  从文档, 各种乱七八糟的教程中过来, 看到laravist的视频, 真心觉得非常干货
贵不贵, 且不说, 只是希望严谨一点....

**Comment by mangoim** [comment]
@JellyBool 看了下你的视频教程，已经更新描述。
